### ISSUE TITLE
Error: package or namespace load failed for ‘rmarkdown’ in rbind(info, getNamespaceInfo(env, "S3methods")):  number of columns of matrices must match (see arg 2) Execution halted

### ISSUE THREAD

**Issue by aderzelle** [liu3zhenlab/KAD#3]
Hello,
getting this error

```
Error: package or namespace load failed for ‘rmarkdown’ in rbind(info, getNamespaceInfo(env, "S3methods")):
 number of columns of matrices must match (see arg 2)
Execution halted

```

thanks

**Comment by aderzelle** [comment]
Solved it, it's the R install on my system that was broken, it's not related to KAD. 
Btw, there is a typo in the shebang of the main Perl script, "use" instead of "usr" ^^

**Comment by liu3zhenlab** [comment]
Good you solved that. Thank you for letting us know.

**Comment by liu3zhenlab** [comment]
"use" has been replaced by "usr". thanks.
