### ISSUE TITLE
interpreting KAD plots for haploid assemblies of heterozygous organisms

### ISSUE THREAD

**Issue by jflot** [liu3zhenlab/KAD#4]
I tried KAD to assess a haploid assembly obtained by merging haplotypes from a heterozygous diploid organism. Here is the initial k-mer plot:
![bild](https://user-images.githubusercontent.com/19376319/84596951-f0e73880-ae60-11ea-92cf-abd64612893c.png)
and here are the final plots I obtain:
![bild](https://user-images.githubusercontent.com/19376319/84596983-17a56f00-ae61-11ea-986e-30a561b29253.png)

Here is how I interpret these plots: the peak at KAD = 0 corresponds to k-mers with single multiplicity (i.e., different between the two haplotypes of my diploid organism) that are found a single time in my assembly (because they are from the haplotype that is represented in that part of my assembly). The peak at KAD = 0.58 (i.e., log2(3/2)) corresponds to k-mers with double multiplicity (i.e. identical in the two haplotypes of my diploid organism) that are found a single time in my assembly (as expected for a haploid assembly of a heterozygous individual). Finally, the peak at KAD = 1.0 corresponds to k-mers with single multiplicity (i.e., different between the two haplotypes of my diploid organism) that are not found in my assembly (because they are from the haplotype that did not make it into my assembly).

That is to say, people using KAD on a haploid assembly of a heterozygous genome should expect to see three peaks at 0, 0.58 and 1.0: this is perfectly fine, and the other peaks (e.g. the one at KAD = -1.0, which represents k-mers in the assembly that are not found in the reads, and the peaks at KAD > 1.0, which represent merged genomic repeats) are the ones they should pay attention to when assessing their assemblies.

Do you agree with my interpretation?

It would be nice to include in the KAD paper such an example of application of KAD to a haploid assembly from an heterozygous organism.

**Comment by jflot** [comment]
Reading again the KAD preprint, I realize that "good k-mers" are defined in Figure 2A as having a KAD score comprised between -0.5 and +0.5. However, as noted above the peak at 0.58 in the case of a haploid assembly of a heterozygous organism corresponds to "good k-mers" as well. Based on that, I think that it would make sense for the "good k-mers" window to be shifted slightly to the right, e.g. from -0.25 to +0.75.

**Comment by liu3zhenlab** [comment]
Thank you for trying KAD. We did not try KAD on haploid assemblies of heterozygous organisms, which we mentioned in the manuscript. But it is very nice to see the KAD result on real data of heterozygous organisms. Your result looks very reasonable and your interpretation is good. Based on your result, adjusting the KAD range of "good k-mers" is necessary. I agree "-0.25 to 0.75" is a good range for your data.
