### ISSUE TITLE
window size on KAD.bed

### ISSUE THREAD

**Issue by aderzelle** [liu3zhenlab/KAD#5]
Hello, 
I wondered if it was possible to have the KAD.bed file of the KAD values not to be the average in25 bp sliding windows, but just 1 bp per line. 

thank you

**Comment by liu3zhenlab** [comment]
The KAD at each bp should be provided in the output file *_5_kad.wig after you run KADdist.pl.

**Comment by aderzelle** [comment]
Perfect! exactly what I needed. 

thanks, great tool
