### ISSUE TITLE
Error in plot.window(...) : need finite 'xlim' values 

### ISSUE THREAD

**Issue by zhangwenda0518** [liu3zhenlab/KAD#6]
Dear author, thank you for your excellent tool. 
I'm using it to compare two assembly results, but in the third step KADcompare.pl , an error occurred. I'm a beginner, I try to solve it ,but i cannot . Could you please give me a solution .

Thanks！

The error is as follows ，

`perl ~/biosoft/genome-evaluation/KAD/KADcompare.pl --set1 hifiasm --set2 peregrine --prefix hifiasm_peregrine 1-KADprofile/1-KADprofile_4_kad.txt

Error in plot.window(...) : need finite 'xlim' values
Calls: diffkadplot -> plot -> plot.default -> localWindow -> plot.window
In addition: Warning messages:
1: In max(y1, y2) : no non-missing arguments to max; returning -Inf
2: In max(y1, y2) : no non-missing arguments to max; returning -Inf
3: In min(x, na.rm = na.rm) :
  no non-missing arguments to min; returning Inf
4: In max(x, na.rm = na.rm) :
  no non-missing arguments to max; returning -Inf
5: In min(x, na.rm = na.rm) :
  no non-missing arguments to min; returning Inf
6: In max(x, na.rm = na.rm) :
  no non-missing arguments to max; returning -Inf
Execution halted
Warning message:
package ‘rmarkdown’ was built under R version 4.1.2

processing file: KADcompare.report.Rmd
Quitting from lines 133-143 (KADcompare.report.Rmd)
Error in plot.window(...) : need finite 'xlim' values
Calls: render ... diffkadplot -> plot -> plot.default -> localWindow -> plot.window
Execution halted`

**Comment by liu3zhenlab** [comment]
could you show the result from `head 1-KADprofile/1-KADprofile_4_kad.txt`?

**Comment by zhangwenda0518** [comment]
thanks for your reply!
head 1-KADprofile/1-KADprofile_4_kad.txt

Kmer    reads   hifiasm peregrine       hifiasm.KAD     peregrine.KAD
AAAAAAAAAAAAAAAAAAAAAAAAA       1695152 1269    1269    2.518   2.518
AAAAAAAAAAAAAAAAAAAAAAAAC       35290   62      62      1.275   1.275
AAAAAAAAAAAAAAAAAAAAAAAAG       14113   44      44      0.452   0.452
AAAAAAAAAAAAAAAAAAAAAAAAT       51886   93      93      1.251   1.251
AAAAAAAAAAAAAAAAAAAAAAACA       25514   30      30      1.834   1.834
AAAAAAAAAAAAAAAAAAAAAAACC       7545    21      21      0.602   0.602
AAAAAAAAAAAAAAAAAAAAAAACG       1590    2       2       1.383   1.383
AAAAAAAAAAAAAAAAAAAAAAACT       7746    31      31      0.098   0.098
AAAAAAAAAAAAAAAAAAAAAAAGA       9931    36      36      0.238   0.238

**Comment by liu3zhenlab** [comment]
The KAD file looks good. Did you have an output file with the suffix of ".bincount.txt"? If yes, do you mind sending it to me at liu3zhen@ksu.edu?

**Comment by zhangwenda0518** [comment]
I am sorry to be back so late. I find the ".bincount.txt" is empty of the resoult KADcompare.pl  

Today I  succes to run the example data and another the two assembly result。

however ，I still miss the issues 。

 After，I  read the 1-kadprofile _ kadprofile.report.html generated in the first step.
I find many useful information  and    a question that **the same resoult bewteen two assembly**

Data | Total | Good | Error | OverRep | LowUnderRep | HighUnderRep
hifiasm.KAD | 197460835 | 186932100 | 248997 | 78880 | 1160546 | 613934
peregrine.KAD | 197460835 | 186932100 | 248997 | 78880 | 1160546 | 613934

then I carefully compare the  3 and 4 columns  of  1-KADprofile/1-KADprofile_4_kad.txt 
there are no different ，so the error happened likes before
**1: In max(y1, y2) : no non-missing arguments to max; returning -Inf
2: In max(y1, y2) : no non-missing arguments to max; returning -Inf**

I tried to modify the values 3 and 4 columns  of  1-KADprofile/1-KADprofile_4_kad.txt  to make it different，final ，it runs well！，I think this is the reason for this errors.

Thanks ！Best wish to you ！
