### ISSUE TITLE
ERROR: can not find a reasonable cmod

### ISSUE THREAD

**Issue by jannafierst** [liu3zhenlab/KAD#7]
Hello,
thank you for this very useful method and software! I am using KAD to analyze a few nematode assemblies and 2 worked great, one gave this error and died:

o merge k-mer tables
o determine mode of counts of read k-mers
warning: the estimated mode equals 5. reestimate...
warning: the estimated mode equals 5. reestimate...
ERROR: a reasonable cmod should be > 3 * 5; can not find a reasonable cmod. quit

Can you give any insight into what this is, or how I can get around it? Thank you!

**Comment by liu3zhenlab** [comment]
The program examines the distribution of k-mer abundance and identifies the peak, which represents the sequencing depth. If the peak (cmod) is between 1-5, it usually indicates that lots of k-mers contains sequencing errors. Then the scanning for the cmod will be restarted. If the cmod identified is too small, sequencing data might not have a sufficient depth, contamination, or other issues. Hope this helps.

**Comment by jannafierst** [comment]
Okay, thanks for the quick reply! This library had a lot of microbial contamination we had to scrub out of the assembly, I'm re-trying with only reads that align to the assembly. I'll see if that works.

**Comment by liu3zhenlab** [comment]
Interesting strategy. Let me know how it works.

**Comment by jannafierst** [comment]
It worked! Thanks again for this handy method & tool - everything from installation to execution was seamless, paper and documentation really well done.
